<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mongo" nsURI="https://geckoprojects.org/model/mongo/1.0" nsPrefix="mongo">
  <eClassifiers xsi:type="ecore:EDataType" name="EDocument" instanceClassName="org.bson.Document"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EBsonDocument" instanceClassName="org.bson.BsonDocument"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EMongoCollection" instanceTypeName="com.mongodb.client.MongoCollection&lt;org.eclipse.emf.ecore.EObject>"/>
  <eClassifiers xsi:type="ecore:EDataType" name="ECursor" instanceTypeName="com.mongodb.client.MongoCursor&lt;org.eclipse.emf.ecore.EObject>"/>
  <eClassifiers xsi:type="ecore:EClass" name="EMongoQuery">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" eType="#//EBsonDocument"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="projection" eType="#//EDocument"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="projectionOnly" eType="#//EDocument"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sort" eType="#//EDocument"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="skip" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="limit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="batchSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
        defaultValueLiteral="1000"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EMongoCursor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cursor" eType="#//ECursor"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="collection" eType="#//EMongoCollection"/>
  </eClassifiers>
</ecore:EPackage>
